config/routes.rb
Rails.application.routes.draw do
  resources :cities do
      resources :localities
      end
      
    get 'localities', to: 'localities#index', as: :custom_search
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
has_many :localities
validates :name, presence: true, uniqueness: true, length: { minimum: 3 }
end

app/models/locality.rb
class Locality < ApplicationRecord
belongs_to :city
validates :name, :city, :latitude, :longitude, presence: true
validates :name, length: { minimum: 3 }
validates :longitude, :latitude, uniqueness: true
validates_associated :city
    
    require 'csv'
    
    def self.import(filepath)
        CSV.foreach(filepath, headers: ['name', 'city', 'latitude', 'longitude']) do |row|
        
            row_hash = row.to_hash
            Locality.create! row_hash.merge(city: City.find_or_create_by(name: row_hash['city']))
            end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :get_city, except: :index
  before_action :set_locality, only: [:show, :edit, :update, :destroy]
  
  # GET /cities/1/localities
  # GET /cities/1/localities.json
  def index
    if params[:city_id]
        @city = get_city
        @localities = @city.localities
    end
    
  # This will help us return a locality for given vales of Latitude and Longitude
    if longitude = params[:longitude] and latitude = params[:latitude]
        @localities = Locality.where({longitude: longitude, latitude: latitude})
    end
 
  # This will help us return localities matching given name
    if name = params[:name]
        @localities = Locality.where("name LIKE ?", "%#{name}%")
    end
  end

  # GET /cities/1/localities/1
  # GET /cities/1/localities/1.json
  def show
      @locality = @city.localities.find(params[:id])
  end

  # GET /cities/1/localities/new
  def new
    @locality = @city.localities.build
  end

  # GET /cities/1/localities/1/edit
  def edit
      @locality = @city.localities.find(params[:id])
  end

  # POST /cities/1/localities
  # POST /cities/1/localities.json
  def create
    
    @locality = @city.localities.create(locality_params)
    
    respond_to do |format|
      if @locality.save
        format.html { redirect_to [@city, @locality], notice: 'Locality was successfully created.' }
        format.json { render :show, status: :created, location: [@city, @locality] }
      else
        format.html { render :new }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1/localities/1
  # PATCH/PUT /cities/1/localities/1.json
  def update
    @locality = @city.localities.find(params[:id])
    respond_to do |format|
      if @locality.update(locality_params)
        format.html { redirect_to [@city, @locality], notice: 'Locality was successfully updated.' }
        format.json { render :show, status: :ok, location: [@city, @locality] }
      else
        format.html { render :edit }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1/localities/1
  # DELETE /cities/1/localities/1.json
  def destroy
    @locality.destroy
    respond_to do |format|
      format.html { redirect_to city_localities_url, notice: 'Locality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locality
      @locality = @city.localities.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locality_params
      params.require(:locality).permit(:name, :city_id, :latitude, :longitude, :pincode)
    end
    
    def get_city
        @city = City.find(params[:city_id])        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocationService</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/localities/_form.html.erb
<%= form_with(model: [@city, @locality], local: true) do |form| %>
  <% if locality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(locality.errors.count, "error") %> prohibited this locality from being saved:</h2>

      <ul>
      <% locality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/localities/edit.html.erb
<h1>Editing Locality</h1>

<%= render 'form', locality: @locality %>

<%= link_to 'Show', @locality %> |
<%= link_to 'Back', city_localities_path %>

app/views/localities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Localities</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @localities.each do |locality| %>
      <tr>
        <td><%= link_to 'Show', locality %></td>
        <td><%= link_to 'Edit', edit_city_locality_path(locality) %></td>
        <td><%= link_to 'Destroy', locality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Locality', new_city_locality_path %>

app/views/localities/new.html.erb
<h1>New Locality</h1>

<%= render 'form', locality: @locality %>

<%= link_to 'Back', city_localities_path %>

app/views/localities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_city_locality_path(@locality) %> |
<%= link_to 'Back', city_localities_path %>